radix_frontend:
  pattern: /{accountid}/frontend
  defaults: { _controller: RadixRecruitmentBundle:Frontend:index }

radix_frontend_job_detail:
  pattern: /{accountid}/frontend/job/{id}
  defaults: { _controller: RadixRecruitmentBundle:Frontend:jobDetail }

radix_frontend_job_apply_manual:
  pattern: /{accountid}/frontend/job/{id}/apply
  defaults: { _controller: RadixRecruitmentBundle:Frontend:jobApply }

radix_frontend_job_apply_facebook:
  pattern: /{accountid}/frontend/job/{id}/apply/facebook
  defaults: { _controller: RadixRecruitmentBundle:Frontend:jobApplyFacebook }

radix_frontend_fb_ok:
  pattern: /{accountid}/frontend/fb_ok
  defaults: { _controller: RadixRecruitmentBundle:Frontend:fbOk }

radix_backend:
  pattern: /{accountid}/backend
  defaults: { _controller: RadixRecruitmentBundle:Backend:backend }
  
radix_backend_job_add:
  pattern: /{accountid}/backend/job/add
  defaults: { _controller: RadixRecruitmentBundle:Backend:jobAdd }

radix_backend_job_edit:
  pattern: /{accountid}/backend/job/{id}/edit
  defaults: { _controller: RadixRecruitmentBundle:Backend:jobEdit }

radix_backend_job_delete:
  pattern: /{accountid}/backend/job/{id}/delete
  defaults: { _controller: RadixRecruitmentBundle:Backend:jobDelete }

radix_backend_application_detail:
  pattern: /{accountid}/backend/application/{applicationid}
  defaults: { _controller: RadixRecruitmentBundle:Backend:applicationDetail }



radix_import:
  pattern: /{accountid}/import
  defaults: { _controller: RadixRecruitmentBundle:Import:import }

radix_job_redirect:
  pattern: /job-redirect/{accountid}/{id}
  defaults: { _controller: RadixRecruitmentBundle:Redirect:jobRedirect }
