radix_frontend:
  pattern: /{accountid}/frontend
  defaults: { _controller: RadixRecruitmentBundle:Frontend:frontend }

radix_detail:
  pattern: /{accountid}/job/{guid}
  defaults: { _controller: RadixRecruitmentBundle:Frontend:detail }

radix_backend:
  pattern: /{accountid}/backend
  defaults: { _controller: RadixRecruitmentBundle:Backend:backend }
  
radix_import:
  pattern: /{accountid}/import
  defaults: { _controller: RadixRecruitmentBundle:Import:import }