radix_frontend:
  pattern: /{accountid}/frontend
  defaults: { _controller: RadixRecruitmentBundle:Frontend:frontend }

radix_frontend_advanced:
  pattern: /{accountid}/frontend/advanced
  defaults: { _controller: RadixRecruitmentBundle:Frontend:frontendAdvanced }

radix_detail:
  pattern: /{accountid}/frontend/job/{id}
  defaults: { _controller: RadixRecruitmentBundle:Frontend:detail }

radix_backend:
  pattern: /{accountid}/backend
  defaults: { _controller: RadixRecruitmentBundle:Backend:backend }
  
radix_backend_job_add:
  pattern: /{accountid}/backend/job/add
  defaults: { _controller: RadixRecruitmentBundle:Backend:jobAdd }

radix_backend_job_edit:
  pattern: /{accountid}/backend/job/{id}/edit
  defaults: { _controller: RadixRecruitmentBundle:Backend:jobEdit }

radix_backend_job_delete:
  pattern: /{accountid}/backend/job/{id}/delete
  defaults: { _controller: RadixRecruitmentBundle:Backend:jobDelete }

radix_import:
  pattern: /{accountid}/import
  defaults: { _controller: RadixRecruitmentBundle:Import:import }