radix_default:
  pattern: /
  defaults: { _controller: RadixRecruitmentBundle:Default:index }



radix_frontend:
  pattern: /{accountid}/frontend
  defaults: { _controller: RadixRecruitmentBundle:Frontend:index }

radix_frontend_job_detail:
  pattern: /{accountid}/frontend/job/{id}
  defaults: { _controller: RadixRecruitmentBundle:Frontend:jobDetail }

radix_frontend_job_apply_manual:
  pattern: /{accountid}/frontend/job/{id}/apply
  defaults: { _controller: RadixRecruitmentBundle:Frontend:jobApply }

# This will become deprecated
radix_frontend_job_apply_facebook:
  pattern: /{accountid}/frontend/job/{id}/apply/facebook
  defaults: { _controller: RadixRecruitmentBundle:Frontend:jobApplyFacebook }
# End deprecated

radix_frontend_facebook_connect:
  pattern: /{accountid}/frontend/job/{id}/connect
  defaults: { _controller: RadixRecruitmentBundle:Frontend:facebookConnect }

radix_frontend_fb_ok:
  pattern: /{accountid}/frontend/fb_ok
  defaults: { _controller: RadixRecruitmentBundle:Frontend:fbOk }

radix_frontend_introduced:
  pattern: /{accountid}/frontend/introduced
  defaults: { _controller: RadixRecruitmentBundle:Frontend:introduced }
  methods: [GET, POST]

radix_frontend_social_recruiter:
  pattern: /{accountid}/frontend/social-recruiter
  defaults: { _controller: RadixRecruitmentBundle:Frontend:socialRecruiter }
  methods: [GET, POST]



radix_backend:
  pattern: /{accountid}/backend
  defaults: { _controller: RadixRecruitmentBundle:Backend:index }

radix_backend_jobs:
  pattern: /{accountid}/backend/jobs
  defaults: { _controller: RadixRecruitmentBundle:Backend:jobs }

radix_backend_applications:
  pattern: /{accountid}/backend/applications
  defaults: { _controller: RadixRecruitmentBundle:Backend:applications }

radix_backend_config:
  pattern: /{accountid}/backend/config
  defaults: { _controller: RadixRecruitmentBundle:Backend:config }

radix_backend_job_add:
  pattern: /{accountid}/backend/job/add
  defaults: { _controller: RadixRecruitmentBundle:Backend:jobAdd }

radix_backend_job_edit:
  pattern: /{accountid}/backend/job/{id}/edit
  defaults: { _controller: RadixRecruitmentBundle:Backend:jobEdit }

radix_backend_job_delete:
  pattern: /{accountid}/backend/job/{id}/delete
  defaults: { _controller: RadixRecruitmentBundle:Backend:jobDelete }

radix_backend_job_applications:
  pattern: /{accountid}/backend/job/{id}/applications
  defaults: { _controller: RadixRecruitmentBundle:Backend:jobApplications }

radix_backend_application_detail:
  pattern: /{accountid}/backend/application/{applicationid}
  defaults: { _controller: RadixRecruitmentBundle:Backend:applicationDetail }
  
radix_backend_media:
  pattern: /{accountid}/backend/media
  defaults: { _controller: RadixRecruitmentBundle:Backend:media }

radix_backend_media_add:
  pattern: /{accountid}/backend/media/add
  defaults: { _controller: RadixRecruitmentBundle:Backend:mediaAdd }

radix_backend_media_edit:
  pattern: /{accountid}/backend/media/{mediaid}/edit
  defaults: { _controller: RadixRecruitmentBundle:Backend:mediaEdit }

radix_backend_media_delete:
  pattern: /{accountid}/backend/media/{mediaid}/delete
  defaults: { _controller: RadixRecruitmentBundle:Backend:mediaDelete }


radix_import:
  pattern: /{accountid}/import
  defaults: { _controller: RadixRecruitmentBundle:Import:import }

radix_job_redirect:
  pattern: /job-redirect/{accountid}/{id}
  defaults: { _controller: RadixRecruitmentBundle:Redirect:jobRedirect }


radix_fql_test:
  pattern: /{accountid}/fql
  defaults: { _controller: RadixRecruitmentBundle:Backend:test }


radix_fb_redirect:
  pattern: /{accountid}/fb-redirect/{nextpage}
  defaults: { _controller: RadixRecruitmentBundle:Facebook:redirect }

radix_fb_redirect:
  pattern: /{accountid}/fb-redirect/{nextpage}/{id}
  defaults: { _controller: RadixRecruitmentBundle:Facebook:redirect }