radix_frontend:
  pattern: /{accountid}/frontend
  defaults: { _controller: RadixRecruitmentBundle:Frontend:frontend }

radix_detail:
  pattern: /{accountid}/frontend/job/{guid}
  defaults: { _controller: RadixRecruitmentBundle:Frontend:detail }

radix_backend:
  pattern: /{accountid}/backend
  defaults: { _controller: RadixRecruitmentBundle:Backend:backend }
  
radix_backend_job_add:
  pattern: /{accountid}/backend/job/add
  defaults: { _controller: RadixRecruitmentBundle:Backend:jobAdd }

radix_backend_job_add_success:
  pattern: /{accountid}/backend/job/add/success
  defaults: { _controller: RadixRecruitmentBundle:Backend:jobAddSuccess }

radix_import:
  pattern: /{accountid}/import
  defaults: { _controller: RadixRecruitmentBundle:Import:import }