parameters:
#    radix_recruitment.example.class: Radix\RecruitmentBundle\Example
  radix_facebook_appid: 600850943303218
  radix_facebook_secret: 41938c8ed1d54041769cb346ffac04d2

services:
#    radix_recruitment.example:
#        class: %radix_recruitment.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

  radix.helper.facebook:
    class: Radix\RecruitmentBundle\Helper\FacebookHelper
    arguments: [%radix_facebook_appid%, %radix_facebook_secret%]
    
  radix.helper.carrot:
    class: Radix\RecruitmentBundle\Helper\CarrotHelper
    arguments: ['@service_container']